export interface BeigeProduct {
  slug: string
  name: string
  collection: "beautiful-beige"
  image: string
  landscapeImage: string
  originalImage: string
  origin: string
  finish: string
  bestFor: string[]
  shortDescription: string
  description: string
  seoTitle: string
  seoDescription: string
  keywords: string[]
}

const products: BeigeProduct[] = [
  {
    slug: "avorio-cream",
    name: "Avorio Cream",
    collection: "beautiful-beige",
    image: "/images/beige/square/avorio-cream.jpg",
    landscapeImage: "/images/beige/landscape/avorio-cream.jpg",
    originalImage: "/images/beige/original/avorio-cream.jpg",
    origin: "Italy",
    finish: "Polished",
    bestFor: ["Luxury flooring", "Feature walls", "Villas"],
    shortDescription: "Soft ivory movement for calm, luminous interiors.",
    description: "Avorio Cream marble brings a refined ivory base and gentle natural movement to luxury interiors. Its quiet warmth pairs beautifully with wood, brass, and contemporary architectural details, making it a versatile choice for expansive floors and elegant wall applications.",
    seoTitle: "Avorio Cream Italian Marble | Chandak Marble",
    seoDescription: "Explore Avorio Cream Italian marble for luxury flooring, feature walls, villas, and refined residential interiors from Chandak Marble.",
    keywords: ["avorio cream marble", "ivory Italian marble", "cream marble flooring"],
  },
  {
    slug: "azul-brescia",
    name: "Azul Brescia",
    collection: "beautiful-beige",
    image: "/images/beige/square/azul-brescia.jpg",
    landscapeImage: "/images/beige/landscape/azul-brescia.jpg",
    originalImage: "/images/beige/original/azul-brescia.jpg",
    origin: "Italy",
    finish: "Polished",
    bestFor: ["Statement floors", "Reception areas", "Hospitality"],
    shortDescription: "Distinctive blue-grey character grounded by warm stone tones.",
    description: "Azul Brescia offers a sophisticated blend of cool mineral movement and warm beige depth. This expressive stone creates a considered focal point in reception spaces, hospitality interiors, and high-end residential projects.",
    seoTitle: "Azul Brescia Marble | Premium Italian Stone",
    seoDescription: "Discover Azul Brescia premium Italian marble with distinctive mineral movement for statement floors and luxury hospitality interiors.",
    keywords: ["azul brescia marble", "blue beige marble", "Italian statement stone"],
  },
  {
    slug: "brescia-aurora",
    name: "Brescia Aurora",
    collection: "beautiful-beige",
    image: "/images/beige/square/brescia-aurora.jpg",
    landscapeImage: "/images/beige/landscape/brescia-aurora.jpg",
    originalImage: "/images/beige/original/brescia-aurora.jpg",
    origin: "Italy",
    finish: "Polished",
    bestFor: ["Flooring", "Wall cladding", "Hotels"],
    shortDescription: "Warm beige veining with an elegant, natural rhythm.",
    description: "Brescia Aurora marble adds soft warmth and layered movement to architectural spaces. Its balanced palette works across large-format flooring, wall cladding, luxury hotel suites, and welcoming living areas.",
    seoTitle: "Brescia Aurora Marble | Beige Italian Marble",
    seoDescription: "Shop Brescia Aurora beige Italian marble for flooring, wall cladding, luxury hotels, and elegant residential interiors.",
    keywords: ["brescia aurora marble", "beige Italian marble", "luxury marble cladding"],
  },
  {
    slug: "crema-marfil",
    name: "Crema Marfil",
    collection: "beautiful-beige",
    image: "/images/beige/square/crema-marfil.jpg",
    landscapeImage: "/images/beige/landscape/crema-marfil.jpg",
    originalImage: "/images/beige/original/crema-marfil.jpg",
    origin: "Spain",
    finish: "Polished",
    bestFor: ["Large-format flooring", "Staircases", "Bathrooms"],
    shortDescription: "Timeless creamy beige for seamless, welcoming spaces.",
    description: "Crema Marfil is a classic creamy beige marble chosen for its warmth, versatility, and graceful presence across large surfaces. It brings continuity to floors, staircases, bathrooms, and softly lit residential interiors.",
    seoTitle: "Crema Marfil Marble | Classic Beige Marble Flooring",
    seoDescription: "Find classic Crema Marfil beige marble for large-format flooring, staircases, bathrooms, and timeless luxury interiors.",
    keywords: ["crema marfil marble", "cream beige marble", "beige marble flooring"],
  },
  {
    slug: "crema-senia",
    name: "Crema Senia",
    collection: "beautiful-beige",
    image: "/images/beige/square/crema-senia.jpg",
    landscapeImage: "/images/beige/landscape/crema-senia.jpg",
    originalImage: "/images/beige/original/crema-senia.jpg",
    origin: "Spain",
    finish: "Honed or polished",
    bestFor: ["Contemporary flooring", "Wall panels", "Commercial spaces"],
    shortDescription: "Clean, understated beige with a smooth architectural feel.",
    description: "Crema Senia offers a restrained beige surface that supports modern architecture without overpowering it. Use it for clean-lined floors, wall panels, commercial interiors, and refined hospitality schemes.",
    seoTitle: "Crema Senia Marble | Contemporary Beige Stone",
    seoDescription: "Explore Crema Senia contemporary beige marble for clean architectural flooring, wall panels, and commercial interiors.",
    keywords: ["crema senia marble", "contemporary beige stone", "beige wall cladding"],
  },
  {
    slug: "de-martino-chips",
    name: "De Martino Chips",
    collection: "beautiful-beige",
    image: "/images/beige/square/de-martino-chips.jpg",
    landscapeImage: "/images/beige/landscape/de-martino-chips.jpg",
    originalImage: "/images/beige/original/de-martino-chips.jpg",
    origin: "Italy",
    finish: "Polished",
    bestFor: ["Feature floors", "Retail interiors", "Accent walls"],
    shortDescription: "Playful natural fragments set within a warm neutral field.",
    description: "De Martino Chips introduces expressive mineral fragments to a warm beige foundation. Its distinctive character makes it an excellent choice for feature floors, retail environments, accent walls, and design-led interiors.",
    seoTitle: "De Martino Chips Marble | Italian Designer Stone",
    seoDescription: "Discover De Martino Chips Italian marble, a distinctive designer stone for feature floors, accent walls, and luxury retail interiors.",
    keywords: ["de martino chips marble", "designer Italian marble", "beige feature stone"],
  },
  {
    slug: "dyna-royale",
    name: "Dyna Royale",
    collection: "beautiful-beige",
    image: "/images/beige/square/dyna-royale.jpg",
    landscapeImage: "/images/beige/landscape/dyna-royale.jpg",
    originalImage: "/images/beige/original/dyna-royale.jpg",
    origin: "Imported selection",
    finish: "Polished",
    bestFor: ["Luxury villas", "Feature walls", "Flooring"],
    shortDescription: "Royal warmth and flowing movement for dramatic interiors.",
    description: "Dyna Royale marble creates a sense of depth through flowing natural movement and warm neutral tones. It is suited to statement walls, luxury villas, grand entrances, and carefully detailed flooring schemes.",
    seoTitle: "Dyna Royale Marble | Luxury Beige Marble",
    seoDescription: "See Dyna Royale luxury beige marble for villas, dramatic feature walls, grand entrances, and premium flooring projects.",
    keywords: ["dyna royale marble", "luxury beige marble", "villa feature wall marble"],
  },
  {
    slug: "exposed-concrete",
    name: "Exposed Concrete",
    collection: "beautiful-beige",
    image: "/images/beige/square/exposed-concrete.jpg",
    landscapeImage: "/images/beige/landscape/exposed-concrete.jpg",
    originalImage: "/images/beige/original/exposed-concrete.jpg",
    origin: "Imported selection",
    finish: "Honed",
    bestFor: ["Minimal interiors", "Commercial flooring", "Modern walls"],
    shortDescription: "A tactile neutral interpretation for modern architecture.",
    description: "Exposed Concrete marble balances a quiet neutral palette with tactile mineral texture. Its contemporary character complements minimalist homes, modern offices, hospitality spaces, and architectural wall applications.",
    seoTitle: "Exposed Concrete Marble | Modern Neutral Stone",
    seoDescription: "Explore Exposed Concrete neutral marble for minimalist interiors, modern walls, commercial flooring, and contemporary architecture.",
    keywords: ["exposed concrete marble", "modern neutral marble", "honed architectural stone"],
  },
  {
    slug: "gold-brescia",
    name: "Gold Brescia",
    collection: "beautiful-beige",
    image: "/images/beige/square/gold-brescia.jpg",
    landscapeImage: "/images/beige/landscape/gold-brescia.jpg",
    originalImage: "/images/beige/original/gold-brescia.jpg",
    origin: "Italy",
    finish: "Polished",
    bestFor: ["Luxury flooring", "Bars and lounges", "Feature walls"],
    shortDescription: "Golden mineral movement with a confident, luxurious presence.",
    description: "Gold Brescia marble brings a luminous golden warmth to premium interiors. Its natural movement performs beautifully in feature walls, lounges, bars, statement floors, and hospitality environments that call for understated opulence.",
    seoTitle: "Gold Brescia Marble | Luxury Golden Beige Stone",
    seoDescription: "Shop Gold Brescia luxury golden beige marble for feature walls, statement floors, bars, lounges, and hospitality interiors.",
    keywords: ["gold brescia marble", "golden beige marble", "luxury feature wall stone"],
  },
  {
    slug: "oracle-cream",
    name: "Oracle Cream",
    collection: "beautiful-beige",
    image: "/images/beige/square/oracle-cream.jpg",
    landscapeImage: "/images/beige/landscape/oracle-cream.jpg",
    originalImage: "/images/beige/original/oracle-cream.jpg",
    origin: "Imported selection",
    finish: "Polished",
    bestFor: ["Residential flooring", "Bathrooms", "Wall cladding"],
    shortDescription: "Gentle cream tones for warm, serene interiors.",
    description: "Oracle Cream marble creates a calm, refined foundation for residential interiors. Its gentle cream tones suit flooring, bathrooms, wall cladding, and spaces where natural light and quiet materiality are central to the design.",
    seoTitle: "Oracle Cream Marble | Premium Cream Stone",
    seoDescription: "Discover Oracle Cream premium marble for serene residential flooring, bathrooms, wall cladding, and warm luxury interiors.",
    keywords: ["oracle cream marble", "cream marble stone", "residential marble flooring"],
  },
  {
    slug: "orange-brescia",
    name: "Orange Brescia",
    collection: "beautiful-beige",
    image: "/images/beige/square/orange-brescia.jpg",
    landscapeImage: "/images/beige/landscape/orange-brescia.jpg",
    originalImage: "/images/beige/original/orange-brescia.jpg",
    origin: "Italy",
    finish: "Polished",
    bestFor: ["Accent walls", "Boutique hospitality", "Statement pieces"],
    shortDescription: "Warm orange veining for expressive, design-forward spaces.",
    description: "Orange Brescia marble adds a distinctive sunlit warmth to interiors. Select it for expressive accent walls, boutique hospitality, sculptural details, and statement spaces where natural stone becomes the defining visual element.",
    seoTitle: "Orange Brescia Marble | Expressive Italian Stone",
    seoDescription: "Explore Orange Brescia expressive Italian marble for accent walls, boutique hospitality, statement pieces, and design-led interiors.",
    keywords: ["orange brescia marble", "orange veined Italian marble", "statement marble wall"],
  },
  {
    slug: "ottoman-beige",
    name: "Ottoman Beige",
    collection: "beautiful-beige",
    image: "/images/beige/square/ottoman-beige.jpg",
    landscapeImage: "/images/beige/landscape/ottoman-beige.jpg",
    originalImage: "/images/beige/original/ottoman-beige.jpg",
    origin: "Turkey",
    finish: "Polished",
    bestFor: ["Flooring", "Staircases", "Hotels"],
    shortDescription: "A warm Turkish beige marble with enduring architectural appeal.",
    description: "Ottoman Beige marble offers the generous warmth and dependable elegance of Turkish stone. Its balanced surface suits broad flooring schemes, staircases, hotel interiors, and contemporary homes seeking a welcoming natural palette.",
    seoTitle: "Ottoman Beige Turkish Marble | Chandak Marble",
    seoDescription: "Discover Ottoman Beige Turkish marble for luxury flooring, staircases, hotels, and warm contemporary architectural interiors.",
    keywords: ["ottoman beige marble", "Turkish beige marble", "beige marble staircase"],
  },
  {
    slug: "brescia-verde",
    name: "Brescia Verde",
    collection: "beautiful-beige",
    image: "/images/beige/square/brescia-verde.jpg",
    landscapeImage: "/images/beige/square/brescia-verde.jpg",
    originalImage: "/images/beige/square/brescia-verde.jpg",
    origin: "Imported selection",
    finish: "Polished",
    bestFor: ["Contemporary flooring", "Feature panels", "Office interiors"],
    shortDescription: "Soft green mineral movement across a refined stone surface.",
    description: "Brescia Verde marble introduces a softly green mineral note to the Beautiful Beige palette through subtle natural movement. It is a strong fit for contemporary flooring, feature panels, offices, and modern interiors with restrained contrast.",
    seoTitle: "Brescia Verde Marble | Contemporary Beige Stone",
    seoDescription: "Explore Brescia Verde contemporary marble with green mineral movement for flooring, feature panels, offices, and modern interiors.",
    keywords: ["brescia verde marble", "green beige marble", "contemporary marble flooring"],
  },
  {
    slug: "superior-beige",
    name: "Superior Beige",
    collection: "beautiful-beige",
    image: "/images/beige/square/superior-beige.jpg",
    landscapeImage: "/images/beige/landscape/superior-beige.jpg",
    originalImage: "/images/beige/original/superior-beige.jpg",
    origin: "Imported selection",
    finish: "Polished",
    bestFor: ["Large residences", "Flooring", "Wall cladding"],
    shortDescription: "A quietly premium beige foundation for complete interiors.",
    description: "Superior Beige marble is a versatile architectural stone with a polished, welcoming presence. Use it across connected floors and walls to create a cohesive material language in large residences, hotels, and premium commercial spaces.",
    seoTitle: "Superior Beige Marble | Premium Beige Flooring",
    seoDescription: "Find Superior Beige premium marble for cohesive luxury flooring, wall cladding, large residences, hotels, and commercial spaces.",
    keywords: ["superior beige marble", "premium beige flooring", "beige marble wall cladding"],
  },
  {
    slug: "vanilla-mocha",
    name: "Vanilla Mocha",
    collection: "beautiful-beige",
    image: "/images/beige/square/vanilla-mocha.jpg",
    landscapeImage: "/images/beige/landscape/vanilla-mocha.jpg",
    originalImage: "/images/beige/original/vanilla-mocha.jpg",
    origin: "Imported selection",
    finish: "Polished",
    bestFor: ["Villas", "Living spaces", "Hospitality"],
    shortDescription: "Cream and coffee tones with a rich, inviting character.",
    description: "Vanilla Mocha marble combines creamy lightness with deeper coffee-toned movement. It brings warmth and texture to villas, living spaces, restaurants, and hospitality interiors designed around comfort and refined material contrast.",
    seoTitle: "Vanilla Mocha Marble | Warm Beige Marble",
    seoDescription: "Discover Vanilla Mocha warm beige marble for villas, living spaces, restaurants, hospitality, and inviting luxury interiors.",
    keywords: ["vanilla mocha marble", "warm beige marble", "mocha marble flooring"],
  },
  {
    slug: "vanilla-spider",
    name: "Vanilla Spider",
    collection: "beautiful-beige",
    image: "/images/beige/square/vanilla-spider.jpg",
    landscapeImage: "/images/beige/landscape/vanilla-spider.jpg",
    originalImage: "/images/beige/original/vanilla-spider.jpg",
    origin: "Imported selection",
    finish: "Polished",
    bestFor: ["Feature walls", "Luxury bathrooms", "Statement floors"],
    shortDescription: "Fine web-like veining across a luminous vanilla base.",
    description: "Vanilla Spider marble is defined by delicate web-like veining across a luminous vanilla ground. Its graphic movement makes it ideal for feature walls, luxury bathrooms, statement floors, and carefully framed architectural details.",
    seoTitle: "Vanilla Spider Marble | Veined Beige Stone",
    seoDescription: "Explore Vanilla Spider veined beige marble for feature walls, luxury bathrooms, statement floors, and architectural details.",
    keywords: ["vanilla spider marble", "veined beige marble", "beige bathroom stone"],
  },
]

export const beigeProducts = products

export function getBeigeProductBySlug(slug: string): BeigeProduct | null {
  return products.find((product) => product.slug === slug) ?? null
}

export function getAllBeigeProductSlugs(): string[] {
  return products.map((product) => product.slug)
}
